/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Announcement = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'timestamp' : Time,
});
export const CommitteeMember = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const PrayerTime = IDL.Record({ 'name' : IDL.Text, 'time' : IDL.Text });

export const idlService = IDL.Service({
  'addAnnouncement' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
  'addCommitteeMember' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'deleteAnnouncement' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'deleteCommitteeMember' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'editAnnouncement' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'editCommitteeMember' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'getAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getAnnouncementsSortedByTime' : IDL.Func(
      [],
      [IDL.Vec(Announcement)],
      ['query'],
    ),
  'getCommitteeMembers' : IDL.Func([], [IDL.Vec(CommitteeMember)], ['query']),
  'getCommitteeMembersSortedByRole' : IDL.Func(
      [],
      [IDL.Vec(CommitteeMember)],
      ['query'],
    ),
  'getPrayerTimes' : IDL.Func([], [IDL.Vec(PrayerTime)], ['query']),
  'getPrayerTimesSorted' : IDL.Func([], [IDL.Vec(PrayerTime)], ['query']),
  'updateMultiplePrayerTimes' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      [IDL.Bool],
      [],
    ),
  'updatePrayerTime' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Announcement = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'timestamp' : Time,
  });
  const CommitteeMember = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const PrayerTime = IDL.Record({ 'name' : IDL.Text, 'time' : IDL.Text });
  
  return IDL.Service({
    'addAnnouncement' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'addCommitteeMember' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'deleteAnnouncement' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'deleteCommitteeMember' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'editAnnouncement' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'editCommitteeMember' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'getAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getAnnouncementsSortedByTime' : IDL.Func(
        [],
        [IDL.Vec(Announcement)],
        ['query'],
      ),
    'getCommitteeMembers' : IDL.Func([], [IDL.Vec(CommitteeMember)], ['query']),
    'getCommitteeMembersSortedByRole' : IDL.Func(
        [],
        [IDL.Vec(CommitteeMember)],
        ['query'],
      ),
    'getPrayerTimes' : IDL.Func([], [IDL.Vec(PrayerTime)], ['query']),
    'getPrayerTimesSorted' : IDL.Func([], [IDL.Vec(PrayerTime)], ['query']),
    'updateMultiplePrayerTimes' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        [IDL.Bool],
        [],
      ),
    'updatePrayerTime' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };