/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CommitteeMember {
  'id' : bigint,
  'name' : string,
  'role' : string,
  'phone' : string,
}
export interface Notice { 'id' : bigint, 'title' : string, 'body' : string }
export interface PrayerTime {
  'order' : bigint,
  'name' : string,
  'time' : string,
  'isJuma' : boolean,
}
export interface _SERVICE {
  'addCommitteeMember' : ActorMethod<
    [string, string, string, string],
    [] | [bigint]
  >,
  'addNotice' : ActorMethod<[string, string, string], [] | [bigint]>,
  'deleteCommitteeMember' : ActorMethod<[string, bigint], boolean>,
  'deleteNotice' : ActorMethod<[string, bigint], boolean>,
  'getAllCommitteeMembers' : ActorMethod<[], Array<CommitteeMember>>,
  'getAllNotices' : ActorMethod<[], Array<Notice>>,
  'getAllPrayerTimes' : ActorMethod<[], Array<PrayerTime>>,
  'getCommitteeMember' : ActorMethod<[bigint], [] | [CommitteeMember]>,
  'getNotice' : ActorMethod<[bigint], [] | [Notice]>,
  'getPrayerTime' : ActorMethod<[string], [] | [PrayerTime]>,
  'getPrayerTimesByName' : ActorMethod<[], Array<PrayerTime>>,
  'getPrayerTimesByOrder' : ActorMethod<[], Array<PrayerTime>>,
  'updateCommitteeMember' : ActorMethod<
    [string, bigint, string, string, string],
    boolean
  >,
  'updateMultiplePrayerTimes' : ActorMethod<
    [string, Array<[string, string]>],
    boolean
  >,
  'updateNotice' : ActorMethod<[string, bigint, string, string], boolean>,
  'updatePrayerTime' : ActorMethod<
    [string, string, string, boolean, bigint],
    boolean
  >,
  'verifyAdminPin' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];