/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CommitteeMember = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'phone' : IDL.Text,
});
export const Notice = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'body' : IDL.Text,
});
export const PrayerTime = IDL.Record({
  'order' : IDL.Nat,
  'name' : IDL.Text,
  'time' : IDL.Text,
  'isJuma' : IDL.Bool,
});

export const idlService = IDL.Service({
  'addCommitteeMember' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Opt(IDL.Nat)],
      [],
    ),
  'addNotice' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Opt(IDL.Nat)],
      [],
    ),
  'deleteCommitteeMember' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'deleteNotice' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'getAllCommitteeMembers' : IDL.Func(
      [],
      [IDL.Vec(CommitteeMember)],
      ['query'],
    ),
  'getAllNotices' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
  'getAllPrayerTimes' : IDL.Func([], [IDL.Vec(PrayerTime)], ['query']),
  'getCommitteeMember' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(CommitteeMember)],
      ['query'],
    ),
  'getNotice' : IDL.Func([IDL.Nat], [IDL.Opt(Notice)], ['query']),
  'getPrayerTime' : IDL.Func([IDL.Text], [IDL.Opt(PrayerTime)], ['query']),
  'getPrayerTimesByName' : IDL.Func([], [IDL.Vec(PrayerTime)], ['query']),
  'getPrayerTimesByOrder' : IDL.Func([], [IDL.Vec(PrayerTime)], ['query']),
  'updateCommitteeMember' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateMultiplePrayerTimes' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      [IDL.Bool],
      [],
    ),
  'updateNotice' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updatePrayerTime' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Nat],
      [IDL.Bool],
      [],
    ),
  'verifyAdminPin' : IDL.Func([IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CommitteeMember = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Notice = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'body' : IDL.Text,
  });
  const PrayerTime = IDL.Record({
    'order' : IDL.Nat,
    'name' : IDL.Text,
    'time' : IDL.Text,
    'isJuma' : IDL.Bool,
  });
  
  return IDL.Service({
    'addCommitteeMember' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Opt(IDL.Nat)],
        [],
      ),
    'addNotice' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Opt(IDL.Nat)],
        [],
      ),
    'deleteCommitteeMember' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'deleteNotice' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'getAllCommitteeMembers' : IDL.Func(
        [],
        [IDL.Vec(CommitteeMember)],
        ['query'],
      ),
    'getAllNotices' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
    'getAllPrayerTimes' : IDL.Func([], [IDL.Vec(PrayerTime)], ['query']),
    'getCommitteeMember' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(CommitteeMember)],
        ['query'],
      ),
    'getNotice' : IDL.Func([IDL.Nat], [IDL.Opt(Notice)], ['query']),
    'getPrayerTime' : IDL.Func([IDL.Text], [IDL.Opt(PrayerTime)], ['query']),
    'getPrayerTimesByName' : IDL.Func([], [IDL.Vec(PrayerTime)], ['query']),
    'getPrayerTimesByOrder' : IDL.Func([], [IDL.Vec(PrayerTime)], ['query']),
    'updateCommitteeMember' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateMultiplePrayerTimes' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        [IDL.Bool],
        [],
      ),
    'updateNotice' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updatePrayerTime' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Nat],
        [IDL.Bool],
        [],
      ),
    'verifyAdminPin' : IDL.Func([IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };