/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PrayerTime = IDL.Record({
  'name' : IDL.Text,
  'time' : IDL.Text,
  'enable' : IDL.Bool,
});
export const Announcement = IDL.Record({
  'title' : IDL.Text,
  'date' : IDL.Text,
  'message' : IDL.Text,
});
export const CommitteeMember = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'phoneNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  'addAnnouncement' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'addCommitteeMember' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'deleteAnnouncement' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'deleteCommitteeMember' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'getAllPrayerTimes' : IDL.Func([], [IDL.Vec(PrayerTime)], ['query']),
  'getAnnouncement' : IDL.Func([IDL.Nat], [IDL.Opt(Announcement)], ['query']),
  'getAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getCommitteeMembers' : IDL.Func([], [IDL.Vec(CommitteeMember)], ['query']),
  'getPrayerTime' : IDL.Func([IDL.Text], [IDL.Opt(PrayerTime)], ['query']),
  'getSortedPrayerTimes' : IDL.Func([], [IDL.Vec(PrayerTime)], ['query']),
  'togglePrayerTime' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [IDL.Bool], []),
  'updateMultiplePrayerTimes' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      [IDL.Bool],
      [],
    ),
  'updatePrayerTime' : IDL.Func([IDL.Text, PrayerTime], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PrayerTime = IDL.Record({
    'name' : IDL.Text,
    'time' : IDL.Text,
    'enable' : IDL.Bool,
  });
  const Announcement = IDL.Record({
    'title' : IDL.Text,
    'date' : IDL.Text,
    'message' : IDL.Text,
  });
  const CommitteeMember = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  
  return IDL.Service({
    'addAnnouncement' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'addCommitteeMember' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'deleteAnnouncement' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'deleteCommitteeMember' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'getAllPrayerTimes' : IDL.Func([], [IDL.Vec(PrayerTime)], ['query']),
    'getAnnouncement' : IDL.Func([IDL.Nat], [IDL.Opt(Announcement)], ['query']),
    'getAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getCommitteeMembers' : IDL.Func([], [IDL.Vec(CommitteeMember)], ['query']),
    'getPrayerTime' : IDL.Func([IDL.Text], [IDL.Opt(PrayerTime)], ['query']),
    'getSortedPrayerTimes' : IDL.Func([], [IDL.Vec(PrayerTime)], ['query']),
    'togglePrayerTime' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Bool],
        [],
      ),
    'updateMultiplePrayerTimes' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        [IDL.Bool],
        [],
      ),
    'updatePrayerTime' : IDL.Func([IDL.Text, PrayerTime], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };