/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Notice {
    id: bigint;
    title: string;
    body: string;
}
export interface PrayerTime {
    order: bigint;
    name: string;
    time: string;
    isJuma: boolean;
}
export interface CommitteeMember {
    id: bigint;
    name: string;
    role: string;
    phone: string;
}
export interface backendInterface {
    addCommitteeMember(pin: string, name: string, role: string, phone: string): Promise<bigint | null>;
    addNotice(pin: string, title: string, body: string): Promise<bigint | null>;
    deleteCommitteeMember(pin: string, id: bigint): Promise<boolean>;
    deleteNotice(pin: string, id: bigint): Promise<boolean>;
    getAllCommitteeMembers(): Promise<Array<CommitteeMember>>;
    getAllNotices(): Promise<Array<Notice>>;
    getAllPrayerTimes(): Promise<Array<PrayerTime>>;
    getCommitteeMember(id: bigint): Promise<CommitteeMember | null>;
    getNotice(id: bigint): Promise<Notice | null>;
    getPrayerTime(name: string): Promise<PrayerTime | null>;
    getPrayerTimesByName(): Promise<Array<PrayerTime>>;
    getPrayerTimesByOrder(): Promise<Array<PrayerTime>>;
    updateCommitteeMember(pin: string, id: bigint, name: string, role: string, phone: string): Promise<boolean>;
    updateMultiplePrayerTimes(pin: string, updates: Array<[string, string]>): Promise<boolean>;
    updateNotice(pin: string, id: bigint, title: string, body: string): Promise<boolean>;
    updatePrayerTime(pin: string, name: string, time: string, isJuma: boolean, order: bigint): Promise<boolean>;
    verifyAdminPin(pin: string): Promise<boolean>;
}
import type { CommitteeMember as _CommitteeMember, Notice as _Notice, PrayerTime as _PrayerTime } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCommitteeMember(arg0: string, arg1: string, arg2: string, arg3: string): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.addCommitteeMember(arg0, arg1, arg2, arg3);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCommitteeMember(arg0, arg1, arg2, arg3);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addNotice(arg0: string, arg1: string, arg2: string): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.addNotice(arg0, arg1, arg2);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNotice(arg0, arg1, arg2);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteCommitteeMember(arg0: string, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCommitteeMember(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCommitteeMember(arg0, arg1);
            return result;
        }
    }
    async deleteNotice(arg0: string, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNotice(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNotice(arg0, arg1);
            return result;
        }
    }
    async getAllCommitteeMembers(): Promise<Array<CommitteeMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCommitteeMembers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCommitteeMembers();
            return result;
        }
    }
    async getAllNotices(): Promise<Array<Notice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNotices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNotices();
            return result;
        }
    }
    async getAllPrayerTimes(): Promise<Array<PrayerTime>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPrayerTimes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPrayerTimes();
            return result;
        }
    }
    async getCommitteeMember(arg0: bigint): Promise<CommitteeMember | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommitteeMember(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommitteeMember(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotice(arg0: bigint): Promise<Notice | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotice(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotice(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPrayerTime(arg0: string): Promise<PrayerTime | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrayerTime(arg0);
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrayerTime(arg0);
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPrayerTimesByName(): Promise<Array<PrayerTime>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrayerTimesByName();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrayerTimesByName();
            return result;
        }
    }
    async getPrayerTimesByOrder(): Promise<Array<PrayerTime>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrayerTimesByOrder();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrayerTimesByOrder();
            return result;
        }
    }
    async updateCommitteeMember(arg0: string, arg1: bigint, arg2: string, arg3: string, arg4: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCommitteeMember(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCommitteeMember(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateMultiplePrayerTimes(arg0: string, arg1: Array<[string, string]>): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMultiplePrayerTimes(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMultiplePrayerTimes(arg0, arg1);
            return result;
        }
    }
    async updateNotice(arg0: string, arg1: bigint, arg2: string, arg3: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNotice(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNotice(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updatePrayerTime(arg0: string, arg1: string, arg2: string, arg3: boolean, arg4: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePrayerTime(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePrayerTime(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async verifyAdminPin(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyAdminPin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyAdminPin(arg0);
            return result;
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CommitteeMember]): CommitteeMember | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Notice]): Notice | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PrayerTime]): PrayerTime | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
